# Site settings
title: Anna Nguyen
tag_text: Anna Nguyen
description: I'm Anna Nguyen, a UX Designer based in New York City. I currently work at IBM where I design frictionless experiences for developers using IBM products.
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Elements
  url: /elements/
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Search
  url: /search/
- title: Fork Alembic
  url: https://github.com/daviddarnes/alembic


# Build settings
markdown: kramdown

exclude: ["README.md"]
