# Site settings
title: Anna Nguyen | UX Designer
tag_text: Anna Nguyễn
description: I'm Anna Nguyen, a UX Designer based in New York City. I currently work at IBM where I design frictionless experiences for developers using IBM products.
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome


# Build settings
markdown: kramdown

exclude: ["README.md"]
